(function(){
'use strict';
if(!window.Q_ARPG){console.warn('[QUETOPIA] SIGNAL 017 QoL host missing');return}
const Q=window.Q_ARPG,S=Q.state;
if(!Array.isArray(S.armory))S.armory=[null,null,null];
const clone=o=>JSON.parse(JSON.stringify(o));
function note(s,c='#72eaff'){let box=document.getElementById('qAdvToast');if(!box)return;let d=document.createElement('div');d.style.color=c;d.textContent=s;box.prepend(d);setTimeout(()=>d.remove(),2800)}
function unsafe(){try{return running&&enemies.some(e=>!e.dead&&e.g.position.distanceTo(player.position)<6)}catch(e){return false}}
function allItems(){return[...S.inv,...S.stash,...Object.values(S.equip).filter(Boolean)]}
function saveArmory(i){S.armory[i]={name:S.armory[i]?.name||['PRISM RIG','VEIL RIG','MYCELIAL RIG'][i],mastery:S.mastery,goal:S.goal,passive:clone(S.passive),skills:clone(S.skills),gear:Object.fromEntries(Object.entries(S.equip).map(([k,v])=>[k,v?.id||null]))};Q.save();renderArmory();note('ARMORY '+(i+1)+' CAPTURED','#ffd16b')}
function loadArmory(i){let a=S.armory[i];if(!a)return note('ARMORY SLOT IS EMPTY','#ff9a70');if(unsafe())return note('ARMORY SWAP LOCKED DURING COMBAT','#ff6f70');let pool=allItems(),used=new Set(),eq={};for(const slot of Object.keys(S.equip)){let id=a.gear?.[slot],it=id?pool.find(x=>x.id===id&&x.slot===slot):null;if(it){eq[slot]=it;used.add(it.id)}else eq[slot]=null}let rest=pool.filter(x=>!used.has(x.id));S.equip=eq;S.inv=rest.slice(0,36);S.stash=rest.slice(36,196);S.mastery=a.mastery||'UNBOUND';S.goal=a.goal||'PRISM';S.passive=clone(a.passive);S.skills=clone(a.skills);Q.save();try{Q.open('gear')}catch(e){};renderArmory();renderAnalyzer();note('ARMORY '+(i+1)+' ACQUIRED','#72eaff')}
function renameArmory(i){let a=S.armory[i]||{name:['PRISM RIG','VEIL RIG','MYCELIAL RIG'][i]},n=prompt('Name this armory loadout',a.name);if(!n)return;if(!S.armory[i])S.armory[i]={name:n,mastery:S.mastery,goal:S.goal,passive:clone(S.passive),skills:clone(S.skills),gear:Object.fromEntries(Object.entries(S.equip).map(([k,v])=>[k,v?.id||null]))};else S.armory[i].name=n.slice(0,24);Q.save();renderArmory()}
function resetPassives(){if(unsafe())return note('RESPEC LOCKED DURING COMBAT','#ff6f70');let n=Object.keys(S.passive.nodes||{}).filter(x=>x!=='root'&&S.passive.nodes[x]).length;if(!n)return;S.passive.points=(S.passive.points||0)+n;S.passive.nodes={root:1};Q.save();document.querySelector('#qMenuHead .qTab[data-page="tree"]')?.click();note('PASSIVE WEB REFUNDED · '+n+' POINTS','#72eaff')}
function resetSkills(){if(unsafe())return note('RESPEC LOCKED DURING COMBAT','#ff6f70');let n=0;for(const st of Object.values(S.skills||{})){for(const r of Object.values(st.nodes||{}))n+=r||0;st.points=(st.points||0)+Object.values(st.nodes||{}).reduce((a,b)=>a+(b||0),0);st.nodes={};st.supports=[]}Q.save();document.querySelector('[data-adv="skills"]')?.click();note('ALL SKILL TREES REFUNDED · '+n+' POINTS','#72eaff')}
function gearScore(){let n=0;for(const it of Object.values(S.equip)){if(!it)continue;n+=(it.rarity||0)*12+(it.ilvl||0);for(const a of it.affixes||[])n+=(a.tier||0)*6;if(it.lp)n+=it.lp*14}return Math.round(n)}
function renderAnalyzer(){let el=document.getElementById('qAnalysisCard');if(!el)return;let c=Q.combined(),off=Math.round((c.damage||0)+(c.prism||0)*.55+(c.boss||0)*.35+(c.overload||0)*1.6),sustain=Math.round((c.wardkill||0)*9+(c.manakill||0)*5+(c.regen||0)*8),economy=Math.round((c.fortune||0)+(c.forge||0)*.8),g=gearScore();let identity=(c.prism||0)>Math.max(c.boss||0,c.mycelial||0)?'PRISM CASCADE':(c.mycelial||0)>(c.boss||0)?'MYCELIAL CONTROL':'VEIL HUNTER';el.innerHTML=`<b>${identity}</b><div>GEAR SIGNAL <strong>${g}</strong></div><div>OFFENSE <strong>${off}</strong> · SUSTAIN <strong>${sustain}</strong></div><div>LOOT / FORGE <strong>${economy}</strong></div><small>All ${Math.round(c.damage||0)}% · Prism ${Math.round(c.prism||0)}% · Boss ${Math.round(c.boss||0)}% · Overload ${Math.round(c.overload||0)}%</small>`}
const css=document.createElement('style');css.textContent=`
#qArmoryWrap{margin-top:13px;border-top:1px solid #44364e;padding-top:10px}.qArmorySlot{border:1px solid #473852;background:#09070d;margin:6px 0;padding:7px}.qArmorySlot .name{font:800 8px system-ui;letter-spacing:.1em;color:#e2cb91;cursor:pointer}.qArmorySlot .sub{font:7px system-ui!important;letter-spacing:.05em!important;color:#7e7585!important;margin:3px 0 6px}.qArmoryActions{display:flex;gap:4px}.qArmoryActions button{flex:1}.qAnalysis{margin-top:10px;padding:9px;border:1px solid #3c3047;background:radial-gradient(circle at 20% 0,#161228,#08070d);font:8px/1.55 system-ui;color:#a9a0b0}.qAnalysis b{display:block;color:#72eaff;font:900 9px Georgia,serif;letter-spacing:.1em;margin-bottom:5px}.qAnalysis strong{color:#e9d292}.qAnalysis small{color:#777080}.qPotential{display:inline-block;margin-left:5px;border:1px solid currentColor;padding:1px 4px;font:800 7px system-ui;letter-spacing:.05em}.qRespecRow{display:flex;gap:6px;margin:7px 0 10px}.qFilterBypass{position:fixed;right:22px;bottom:198px;z-index:8;pointer-events:none;font:800 7px system-ui;letter-spacing:.12em;color:#777181;text-shadow:0 2px 4px #000}.qFilterBypass.on{color:#72eaff}`;document.head.appendChild(css);
const equipPanel=document.querySelector('#qGearAdv .qAdvCols > .qPanel');if(equipPanel){let a=document.createElement('div');a.id='qArmoryWrap';a.innerHTML='<h3>RECEIVER ARMORY</h3><div id="qArmorySlots"></div><div id="qAnalysisCard" class="qAnalysis"></div>';equipPanel.appendChild(a)}
function renderArmory(){let host=document.getElementById('qArmorySlots');if(!host)return;host.innerHTML='';for(let i=0;i<3;i++){let a=S.armory[i],d=document.createElement('div');d.className='qArmorySlot';d.innerHTML=`<div class="name">${a?.name||'EMPTY SIGNAL '+(i+1)}</div><div class="sub">${a?(a.mastery+' · '+a.goal):'SAVE A BUILD + EQUIPMENT LOADOUT'}</div><div class="qArmoryActions"><button class="qMiniBtn save">SAVE</button><button class="qMiniBtn load">LOAD</button></div>`;d.querySelector('.name').onclick=()=>renameArmory(i);d.querySelector('.save').onclick=()=>saveArmory(i);d.querySelector('.load').onclick=()=>loadArmory(i);host.appendChild(d)}renderAnalyzer()}
const passHead=document.querySelector('#qPassiveAdv .qTreeHead');if(passHead&&!document.getElementById('qResetPassives')){let b=document.createElement('button');b.id='qResetPassives';b.className='qMiniBtn';b.textContent='REFUND ALL';b.onclick=resetPassives;passHead.appendChild(b)}
const skillHead=document.querySelector('#qSkillsAdv .qTreeHead');if(skillHead&&!document.getElementById('qResetSkills')){let b=document.createElement('button');b.id='qResetSkills';b.className='qMiniBtn';b.textContent='REFUND ALL SKILLS';b.onclick=resetSkills;skillHead.appendChild(b)}
const bypass=document.createElement('div');bypass.id='qFilterBypass';bypass.className='qFilterBypass';bypass.textContent='HOLD X · TEMPORARILY RELAX LOOT FILTER';document.body.appendChild(bypass);
let filterBackup=null;addEventListener('keydown',e=>{if(e.key.toLowerCase()!=='x'||e.repeat||filterBackup)return;filterBackup={preset:S.filter.preset,min:S.filter.min,showMagicWanted:S.filter.showMagicWanted};S.filter.preset='JOURNEY';S.filter.min=0;S.filter.showMagicWanted=true;bypass.classList.add('on');bypass.textContent='LOOT FILTER RELAXED · RELEASE X TO RESTORE'});addEventListener('keyup',e=>{if(e.key.toLowerCase()!=='x'||!filterBackup)return;Object.assign(S.filter,filterBackup);filterBackup=null;bypass.classList.remove('on');bypass.textContent='HOLD X · TEMPORARILY RELAX LOOT FILTER'});
function decoratePotentials(){let cards=document.querySelectorAll('#qCards .qCard');for(const card of cards){if(card.dataset.qpot)return;let name=card.querySelector('b')?.textContent,items=[...S.inv,...S.stash];let it=items.find(x=>x.name===name);if(!it)continue;let meta=card.querySelector('.meta');if(!meta)continue;if(it.lp){let x=document.createElement('span');x.className='qPotential';x.textContent='LP '+it.lp;meta.appendChild(x)}else if(typeof it.fp==='number'&&it.fp>0){let x=document.createElement('span');x.className='qPotential';x.textContent='FP '+it.fp;meta.appendChild(x)}card.dataset.qpot='1'}}
const cardHost=document.getElementById('qCards');if(cardHost)new MutationObserver(()=>{decoratePotentials();renderAnalyzer()}).observe(cardHost,{childList:true,subtree:true});
renderArmory();decoratePotentials();Q.save();console.log('[QUETOPIA] SIGNAL 017 QoL armory layer active');
})();