(function(){
'use strict';
const TAG='SIGNAL 019 · KINETIC CORE';
if(typeof THREE==='undefined'||typeof scene==='undefined'){console.warn('[QUETOPIA] '+TAG+' unavailable');return}
const css=document.createElement('style');css.textContent=`
#q19Status{position:fixed;left:50%;bottom:118px;transform:translateX(-50%);z-index:9;pointer-events:none;padding:6px 11px;border:1px solid #96784b;background:linear-gradient(180deg,#100c17ee,#06060bf2);box-shadow:0 8px 24px #000a,inset 0 1px 0 #ffe7aa20;color:#d9c797;font:800 8px/1.2 system-ui;letter-spacing:.14em;white-space:nowrap;text-shadow:0 1px 3px #000;backdrop-filter:blur(8px)}
#q19Status b{color:#70eaff}.skill.q19Ready{box-shadow:inset 0 0 22px #000,0 0 0 1px #d6b66d,0 0 15px #6deaff38}.skill.q19Ready .icon{filter:saturate(1.15) brightness(1.08)}
#q19AnchorToast{position:fixed;left:50%;top:132px;transform:translate(-50%,0);z-index:10;pointer-events:none;color:#eadfbd;font:900 11px Georgia,serif;letter-spacing:.18em;text-shadow:0 2px 5px #000,0 0 18px #72eaff;opacity:0;transition:.25s}.q19ToastOn{opacity:1!important;transform:translate(-50%,-8px)!important}
`;document.head.appendChild(css);
const status=document.createElement('div');status.id='q19Status';status.innerHTML='<b>SIGNAL 019</b> · LMB MOVE · RMB SIGNAL · Q PRISM · E NOVA · R FRACTURE · SPACE PHASE';document.body.appendChild(status);
const toast=document.createElement('div');toast.id='q19AnchorToast';toast.textContent='SIGNAL ANCHOR STABILIZED';document.body.appendChild(toast);
const fx=[];const activated=new WeakSet();let destA=null,destB=null,last=performance.now(),prevPos=null,trailClock=0,toastTimer=0;
function mat(c,o=.75){return new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending})}
function ring(pos,a,b,c,o=.7,y=.07){let m=new THREE.Mesh(new THREE.RingGeometry(a,b,56),mat(c,o));m.rotation.x=-Math.PI/2;m.position.copy(pos);m.position.y=y;scene.add(m);return m}
function light(pos,c,i=18,life=.45){let l=new THREE.PointLight(c,i,9);l.position.copy(pos).add(new THREE.Vector3(0,1.2,0));scene.add(l);fx.push({kind:'light',o:l,t:0,life})}
function burst(pos,c,n=20){for(let i=0;i<n;i++){let m=new THREE.Mesh(new THREE.SphereGeometry(.025+Math.random()*.035,6,5),mat(i%4===0?0xffffff:c,.86));m.position.copy(pos).add(new THREE.Vector3(0,.2+Math.random()*.25,0));scene.add(m);let a=Math.random()*Math.PI*2,s=.8+Math.random()*2.8;fx.push({kind:'p',o:m,t:0,life:.45+Math.random()*.45,v:new THREE.Vector3(Math.cos(a)*s,1+Math.random()*2.2,Math.sin(a)*s)})}}
function announce(s){toast.textContent=s;toast.classList.remove('q19ToastOn');void toast.offsetWidth;toast.classList.add('q19ToastOn');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('q19ToastOn'),1600)}
function anchorFx(pos){announce('SIGNAL ANCHOR STABILIZED');light(pos,0x68eaff,30,.9);burst(pos,0xa85cff,34);for(let i=0;i<5;i++){let r=ring(pos,.36+i*.15,.44+i*.15,i%2?0x69eaff:0xc05cff,.86-i*.08,.09+i*.006);fx.push({kind:'wave',o:r,t:-i*.055,life:1.35})}let beam=new THREE.Mesh(new THREE.CylinderGeometry(.07,.38,9,18,1,true),mat(0x70eaff,.48));beam.position.copy(pos);beam.position.y=4.5;scene.add(beam);fx.push({kind:'beam',o:beam,t:0,life:1.25})}
function novaFx(pos){light(pos,0xc05cff,18,.4);burst(pos,0x6ceaff,16);for(let i=0;i<3;i++){let r=ring(pos,.42+i*.12,.54+i*.12,i%2?0x6ceaff:0xcc5cff,.82-i*.12,.09);fx.push({kind:'nova',o:r,t:-i*.045,life:.85})}}
function fractureFx(pos){light(pos,0x568cff,16,.65);let a=ring(pos,3.25,3.48,0x67eaff,.72,.075),b=ring(pos,1.72,1.86,0xd05cff,.66,.083);fx.push({kind:'field',o:a,t:0,life:5,phase:0});fx.push({kind:'field',o:b,t:0,life:5,phase:1.4});for(let i=0;i<8;i++){let ang=i/8*Math.PI*2;let m=new THREE.Mesh(new THREE.ConeGeometry(.065,.68,6),mat(i%2?0x68eaff:0xa85cff,.58));m.position.copy(pos).add(new THREE.Vector3(Math.cos(ang)*2.55,.34,Math.sin(ang)*2.55));scene.add(m);fx.push({kind:'spike',o:m,t:0,life:5,phase:ang})}}
function ensureDest(){if(destA)return;destA=ring(new THREE.Vector3(),.28,.36,0x71eaff,.72,.055);destB=ring(new THREE.Vector3(),.06,.11,0xffffff,.76,.06);destA.visible=destB.visible=false}
function destination(t){ensureDest();let active=typeof mouseMoving!=='undefined'&&mouseMoving&&typeof moveTarget!=='undefined';destA.visible=destB.visible=!!active;if(!active)return;destA.position.x=destB.position.x=moveTarget.x;destA.position.z=destB.position.z=moveTarget.z;destA.rotation.z+=.025;destA.scale.setScalar(1+.11*Math.sin(t*7));destB.scale.setScalar(1.1+.18*Math.sin(t*10))}
function cooldowns(){let cards=document.querySelectorAll('.hotbar .skill');if(!cards.length)return;let cds=[typeof fc==='number'?fc:1,typeof pc==='number'?pc:1,typeof qc==='number'?qc:1,typeof ec==='number'?ec:1,typeof dc==='number'?dc:1],mana=typeof manav==='number'?manav:999,need=[1,18,28,34,0];cards.forEach((c,i)=>c.classList.toggle('q19Ready',(cds[i]??1)<=.01&&mana>=need[i]))}
function anchorsNow(){if(typeof anchors==='undefined'||!anchors)return;for(const a of anchors){if(!a||!a.g)continue;if(a.on&&!activated.has(a)){activated.add(a);anchorFx(a.g.position.clone())}}}
function hint(){if(typeof anchors==='undefined'||typeof player==='undefined'||!player)return false;let n=anchors.find(a=>a&&!a.on&&a.g&&a.g.position.distanceTo(player.position)<2.8);if(!n)return false;status.innerHTML='<b>ANCHOR IN RANGE</b> · MOVE CLOSER TO STABILIZE';return true}
try{const n0=nova;nova=function(){let before=typeof qc==='number'?qc:999,p=player?.position?.clone();let r=n0.apply(this,arguments);if(p&&before<=.01&&typeof qc==='number'&&qc>before)novaFx(p);return r};const f0=fracture;fracture=function(){let before=typeof ec==='number'?ec:999,p=(typeof aim!=='undefined'&&aim?.clone)?aim.clone():player?.position?.clone();let r=f0.apply(this,arguments);if(p&&before<=.01&&typeof ec==='number'&&ec>before)fractureFx(p);return r}}catch(e){console.warn('[QUETOPIA] 019 kinetic combat',e)}
function step(now){let dt=Math.min(.05,Math.max(.001,(now-last)/1000));last=now;let t=now/1000;if(typeof player!=='undefined'&&player?.position){if(!prevPos)prevPos=player.position.clone();let v=player.position.clone().sub(prevPos);v.y=0;let sp=v.length()/dt;if(sp>.25){trailClock-=dt;if(trailClock<=0){trailClock=.085;let back=player.position.clone().addScaledVector(v.clone().normalize(),-.36);let m=ring(back,.05,.13,0x5eeaff,.30,.04);fx.push({kind:'trail',o:m,t:0,life:.42})}}prevPos.copy(player.position)}destination(t);anchorsNow();cooldowns();if(!hint())status.innerHTML='<b>SIGNAL 019</b> · LMB MOVE · RMB SIGNAL · Q PRISM · E NOVA · R FRACTURE · SPACE PHASE';for(let i=fx.length-1;i>=0;i--){let f=fx[i];f.t+=dt;let p=Math.max(0,Math.min(1,f.t/f.life));if(f.kind==='p'){f.v.y-=5.2*dt;f.o.position.addScaledVector(f.v,dt);f.o.material.opacity=.86*(1-p)}else if(f.kind==='light'){f.o.intensity*=Math.pow(.05,dt/f.life)}else if(f.kind==='wave'||f.kind==='nova'){if(f.t>=0){let k=1+p*(f.kind==='wave'?6.4:4.8);f.o.scale.set(k,k,k);f.o.material.opacity=.8*(1-p)}}else if(f.kind==='beam'){f.o.material.opacity=.48*(1-p);f.o.scale.x=f.o.scale.z=1+p*.5}else if(f.kind==='field'){f.o.rotation.z+=dt*(f.phase?-.65:.7);f.o.material.opacity=.30+.32*(.5+.5*Math.sin(t*5+f.phase))}else if(f.kind==='spike'){f.o.material.opacity=.25+.32*(.5+.5*Math.sin(t*6+f.phase));f.o.scale.y=.84+.28*(.5+.5*Math.sin(t*5+f.phase))}else if(f.kind==='trail'){let k=1+p*1.7;f.o.scale.set(k,k,k);f.o.material.opacity=.3*(1-p)}if(f.t>=f.life){if(f.o?.parent)f.o.parent.remove(f.o);fx.splice(i,1)}}requestAnimationFrame(step)}
requestAnimationFrame(step);console.log('[QUETOPIA] '+TAG+' active');
})();