'use client'

import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

type Profile={username:string;display_name:string;bio:string;city:string;region:string;public_contact:string;is_18_plus:boolean}
type Match={id:string;compatibility_score:number;explanation:string;reasons:any;status:string}
type Msg={role:'user'|'assistant';content:string}
const EMPTY:Profile={username:'',display_name:'',bio:'',city:'',region:'',public_contact:'',is_18_plus:false}
const SITE='https://quetopia-collab.vercel.app'

export default function Home(){
 const [user,setUser]=useState<any>(null),[authMode,setAuthMode]=useState<'in'|'up'>('in'),[busy,setBusy]=useState(false)
 const [tab,setTab]=useState('home'),[notice,setNotice]=useState(''),[error,setError]=useState(''),[unconfirmed,setUnconfirmed]=useState('')
 const [profile,setProfile]=useState<Profile>(EMPTY),[profileLoading,setProfileLoading]=useState(false),[profileBusy,setProfileBusy]=useState(false),[evaporating,setEvaporating]=useState(false),[homeFlash,setHomeFlash]=useState(false)
 const [matches,setMatches]=useState<Match[]>([]),[projects,setProjects]=useState<any[]>([]),[messages,setMessages]=useState<Msg[]>([]),[chat,setChat]=useState('')

 useEffect(()=>{supabase.auth.getSession().then(({data})=>setUser(data.session?.user??null));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>subscription.unsubscribe()},[])
 useEffect(()=>{if(user){void loadProfile();void loadMatches();void loadProjects()}},[user])
 useEffect(()=>{if(user&&tab==='profile')void loadProfile()},[tab,user])
 const flash=(s:string)=>{setError('');setNotice(s);setTimeout(()=>setNotice(''),2600)}
 const fail=(e:any)=>{setNotice('');setError(e?.message??String(e))}

 async function sign(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setNotice('');const fd=new FormData(e.currentTarget),email=String(fd.get('email')),password=String(fd.get('password'));setUnconfirmed(email);try{if(authMode==='up'){const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:SITE}});if(error)throw error;setNotice(data.session?'Welcome to Quetopia.':'Check your email to verify your account, then come back and sign in.')}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;setTab('home')}}catch(x:any){fail(x)}finally{setBusy(false)}}
 async function resend(){if(!unconfirmed)return;setBusy(true);const {error}=await supabase.auth.resend({type:'signup',email:unconfirmed,options:{emailRedirectTo:SITE}});setBusy(false);if(error)return fail(error);flash('Fresh confirmation email sent.')}

 async function loadProfile(){if(!user)return;setProfileLoading(true);setError('');try{const {data,error}=await supabase.from('profiles').select('username,display_name,bio,city,region,public_contact,is_18_plus').eq('user_id',user.id).maybeSingle();if(error)throw error;setProfile(data?{username:data.username??'',display_name:data.display_name??'',bio:data.bio??'',city:data.city??'',region:data.region??'',public_contact:data.public_contact??'',is_18_plus:!!data.is_18_plus}:EMPTY)}catch(x:any){fail(x)}finally{setProfileLoading(false)}}
 async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user)return;setProfileBusy(true);setError('');try{const p={user_id:user.id,username:profile.username.trim(),display_name:profile.display_name.trim(),bio:profile.bio.trim(),city:profile.city.trim(),region:profile.region.trim(),country:'US',public_contact:profile.public_contact.trim(),is_18_plus:profile.is_18_plus};const {data,error}=await supabase.from('profiles').upsert(p,{onConflict:'user_id'}).select('username,display_name,bio,city,region,public_contact,is_18_plus').single();if(error)throw error;setProfile({...p,...data});setEvaporating(true);setTimeout(()=>{setEvaporating(false);setTab('home');setHomeFlash(true);window.scrollTo({top:0,behavior:'instant' as ScrollBehavior});setTimeout(()=>setHomeFlash(false),2200)},900)}catch(x:any){fail(x)}finally{setProfileBusy(false)}}

 async function loadProjects(){if(!user)return;const {data}=await supabase.from('projects').select('*,project_roles(*)').eq('owner_user_id',user.id).order('created_at',{ascending:false});setProjects(data??[])}
 async function loadMatches(){const {data}=await supabase.from('matches').select('*').order('compatibility_score',{ascending:false});setMatches(data??[])}
 async function generateMatches(){const {data,error}=await supabase.functions.invoke('ai-generate-matches',{body:{}});if(error)return fail(error);flash(`Scanned ${data?.evaluated??0} opportunities.`);void loadMatches()}
 async function decide(id:string,decision:'approve'|'reject'){const {error}=await supabase.functions.invoke('match-decision',{body:{match_id:id,decision}});if(error)return fail(error);flash('Signal saved.');void loadMatches()}
 async function sendChat(){if(!chat.trim())return;const next=[...messages,{role:'user',content:chat.trim()} as Msg];setMessages(next);setChat('');const {data,error}=await supabase.functions.invoke('ai-onboarding',{body:{messages:next}});if(error)return fail(error);setMessages([...next,{role:'assistant',content:data.message}])}
 async function syncAI(){const {error}=await supabase.functions.invoke('ai-profile-sync',{body:{messages}});if(error)return fail(error);flash('Your AI signal is updated.')}
 async function createProject(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user)return;const fd=new FormData(e.currentTarget);const p={owner_user_id:user.id,title:String(fd.get('title')),description:String(fd.get('description')||''),style_tags:String(fd.get('styles')||'').split(',').map(x=>x.trim()).filter(Boolean),location_mode:String(fd.get('location_mode')||'either'),city:String(fd.get('city')||''),region:String(fd.get('region')||''),country:'US',compensation:String(fd.get('compensation')||'open'),timeline_text:String(fd.get('timeline')||''),status:'active'};const {data:project,error}=await supabase.from('projects').insert(p).select('*').single();if(error)return fail(error);const {error:roleError}=await supabase.from('project_roles').insert({project_id:project.id,role_name:String(fd.get('role_name')),description:String(fd.get('role_description')||''),required_skills:String(fd.get('required_skills')||'').split(',').map(x=>x.trim()).filter(Boolean),preferred_styles:String(fd.get('preferred_styles')||'').split(',').map(x=>x.trim()).filter(Boolean)});if(roleError)return fail(roleError);flash('Opportunity launched into Quetopia.');e.currentTarget.reset();void loadProjects()}

 if(!user)return <main className="landing"><div className="ambient a1"/><div className="ambient a2"/><section className="loginPortal"><div className="sigil">Q</div><div className="eyebrow">QUETOPIA // COLLAB NETWORK</div><h1>FIND YOUR<br/><span>CREATIVE SIGNAL.</span></h1><p>AI-powered collaboration for musicians, creators and beautiful weirdos.</p><form className="glass" onSubmit={sign}>{notice&&<div className="notice">{notice}</div>}{error&&<div className="error">{error}</div>}<input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password" minLength={8} required/><button className="primary" disabled={busy}>{busy?'TUNING SIGNAL…':authMode==='in'?'ENTER QUETOPIA':'CREATE ACCOUNT'}</button>{authMode==='in'&&/email not confirmed/i.test(error)&&<button type="button" className="textBtn" onClick={resend}>Resend confirmation</button>}<button type="button" className="textBtn" onClick={()=>{setAuthMode(authMode==='in'?'up':'in');setError('');setNotice('')}}>{authMode==='in'?'New signal? Create account':'Already connected? Sign in'}</button></form></section></main>

 const name=profile.display_name||profile.username||'Creator',location=[profile.city,profile.region].filter(Boolean).join(', ')
 return <main className="shell"><div className="noise"/><header className="top"><button className="logo" onClick={()=>setTab('home')}>Q</button><nav>{[['home','Home'],['matches','Matches'],['ai','My AI'],['projects','Projects'],['profile','Profile']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</nav><button className="signout" onClick={()=>supabase.auth.signOut()}>↗</button></header>
 {notice&&<div className="toast">✦ {notice}</div>}{error&&<div className="toast bad">{error}</div>}

 {tab==='home'&&<section className="home"><div className={'identity '+(homeFlash?'flash':'')}><div className="avatar">{name[0]?.toUpperCase()}</div><div><div className="eyebrow">YOUR QUETOPIA SIGNAL</div><h1>{name}</h1>{profile.username&&<div className="handle">@{profile.username}</div>}{location&&<div className="location">◉ {location}</div>}</div></div>{homeFlash&&<div className="shift">PROFILE UPDATED <b>YOUR SIGNAL SHIFTED ✦</b></div>}<div className="profileCard glass"><div className="cardHead"><div><div className="eyebrow">PUBLIC SIGNAL</div><h2>Your profile</h2></div><button className="ghost" onClick={()=>setTab('profile')}>EDIT</button></div><p>{profile.bio||'Add a bio so collaborators immediately understand your sound, vision and vibe.'}</p><div className="chips">{location&&<span>📍 {location}</span>}{profile.public_contact&&<span>✉ {profile.public_contact}</span>}{profile.is_18_plus&&<span>✓ 18+</span>}</div></div><div className="metrics"><button className="metric" onClick={()=>setTab('matches')}><small>MATCH SIGNALS</small><strong>{matches.length}</strong><span>Explore connections →</span></button><button className="metric" onClick={()=>setTab('projects')}><small>ACTIVE PROJECTS</small><strong>{projects.length}</strong><span>Build something →</span></button></div></section>}

 {tab==='profile'&&<section className={'profileStage '+(evaporating?'evaporate':'')}>{profileLoading?<div className="profileLoader"><div className="loaderOrb"/><p>RECALLING YOUR SIGNAL…</p></div>:<form className="glass profileForm" onSubmit={saveProfile}><div className="eyebrow">PUBLIC PROFILE</div><h1>Edit your signal</h1><p className="sub">Your saved information is loaded first. Change only what you want.</p><div className="two"><input value={profile.username} onChange={e=>setProfile({...profile,username:e.target.value})} placeholder="Username" required/><input value={profile.display_name} onChange={e=>setProfile({...profile,display_name:e.target.value})} placeholder="Display name"/><input value={profile.city} onChange={e=>setProfile({...profile,city:e.target.value})} placeholder="City"/><input value={profile.region} onChange={e=>setProfile({...profile,region:e.target.value})} placeholder="State / region"/></div><textarea rows={5} value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})} placeholder="Bio — what do you create, what is your vibe, who do you want to meet?"/><input value={profile.public_contact} onChange={e=>setProfile({...profile,public_contact:e.target.value})} placeholder="Public contact email or method"/><label className="check"><input type="checkbox" checked={profile.is_18_plus} onChange={e=>setProfile({...profile,is_18_plus:e.target.checked})}/> I confirm I am 18 or older</label><button className="primary save" disabled={profileBusy}>{profileBusy?'SAVING TO THE SIGNAL…':'SAVE + RETURN HOME'}</button></form>}{evaporating&&<div className="portal"><div className="ring"/><b>SAVED TO QUETOPIA</b></div>}</section>}

 {tab==='matches'&&<section className="stack"><div className="glass heroCard"><div className="eyebrow">AI MATCH ENGINE</div><h1>Your creative orbit</h1><p>Compatibility is personal—not a popularity score.</p><button className="primary" onClick={generateMatches}>SCAN THE NETWORK</button></div>{matches.length===0&&<div className="empty glass">No signals yet. Complete your profile, teach My AI, then scan the network.</div>}{matches.map(m=><article className="match glass" key={m.id}><div className="score">{m.compatibility_score}<small>%</small></div><p>{m.explanation}</p><div className="chips">{Array.isArray(m.reasons?.items)&&m.reasons.items.map((x:string)=><span key={x}>{x}</span>)}</div>{m.status==='proposed'&&<div className="actions"><button className="primary" onClick={()=>decide(m.id,'approve')}>CONNECT</button><button className="ghost" onClick={()=>decide(m.id,'reject')}>PASS</button></div>}</article>)}</section>}

 {tab==='ai'&&<section className="glass ai"><div className="eyebrow">YOUR PRIVATE COLLABORATION INTELLIGENCE</div><h1>My AI</h1><p className="sub">Teach it your sound, taste, goals and deal-breakers. This structured profile stays private.</p><div className="chat">{messages.map((m,i)=><div className={'bubble '+m.role} key={i}>{m.content}</div>)}</div><textarea rows={4} value={chat} onChange={e=>setChat(e.target.value)} placeholder="Tell your AI what you're creating and who you want to find…"/><div className="actions"><button className="primary" onClick={sendChat}>SEND SIGNAL</button><button className="ghost" disabled={!messages.length} onClick={syncAI}>SYNC MY AI</button></div></section>}

 {tab==='projects'&&<section className="stack"><form className="glass projectForm" onSubmit={createProject}><div className="eyebrow">LAUNCH A COLLABORATION</div><h1>Create opportunity</h1><input name="title" placeholder="Project title" required/><textarea name="description" placeholder="What are you creating?"/><div className="two"><input name="role_name" placeholder="Role needed — guitarist, editor…" required/><input name="styles" placeholder="Styles — psychedelic, funk…"/><input name="required_skills" placeholder="Required skills"/><input name="preferred_styles" placeholder="Preferred styles"/><select name="location_mode"><option value="either">Local or remote</option><option value="local">Local only</option><option value="remote">Remote only</option></select><select name="compensation"><option value="open">Compensation open</option><option value="paid">Paid</option><option value="unpaid">Unpaid</option><option value="barter">Barter</option></select><input name="city" placeholder="City"/><input name="region" placeholder="State / region"/></div><textarea name="role_description" placeholder="What do you need from this person?"/><input name="timeline" placeholder="Timeline"/><button className="primary">LAUNCH INTO QUETOPIA</button></form>{projects.map(p=><article className="glass" key={p.id}><div className="eyebrow">ACTIVE PROJECT</div><h2>{p.title}</h2><p>{p.description}</p><div className="chips">{p.project_roles?.map((r:any)=><span key={r.id}>{r.role_name}</span>)}</div></article>)}</section>}
 </main>
}
