'use client'

import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

type Msg = { role:'user'|'assistant'; content:string }
type Match = { id:string; compatibility_score:number; explanation:string; reasons:any; status:string }
type Profile = { username:string; display_name:string; bio:string; city:string; region:string; public_contact:string; is_18_plus:boolean }
const SITE_URL='https://quetopia-collab.vercel.app'
const EMPTY_PROFILE:Profile={username:'',display_name:'',bio:'',city:'',region:'',public_contact:'',is_18_plus:false}

export default function Home(){
  const [user,setUser]=useState<any>(null),[authMode,setAuthMode]=useState<'in'|'up'>('in'),[busy,setBusy]=useState(false)
  const [notice,setNotice]=useState(''),[error,setError]=useState(''),[unconfirmedEmail,setUnconfirmedEmail]=useState(''),[tab,setTab]=useState('home')
  const [messages,setMessages]=useState<Msg[]>([]),[chat,setChat]=useState(''),[matches,setMatches]=useState<Match[]>([]),[projects,setProjects]=useState<any[]>([])
  const [profile,setProfile]=useState<Profile>(EMPTY_PROFILE),[profileBusy,setProfileBusy]=useState(false),[profileExit,setProfileExit]=useState(false),[homeFlash,setHomeFlash]=useState(false)

  useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user??null));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>subscription.unsubscribe()},[])
  useEffect(()=>{if(user){loadMatches();loadProjects();loadProfile()}},[user])
  function fail(e:any){setNotice('');const msg=e?.message??String(e);setError(msg);if(/email not confirmed/i.test(msg)&&unconfirmedEmail)setNotice('Your email still needs verification.')}
  function flash(s:string){setError('');setNotice(s)}

  async function sign(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setNotice('');const fd=new FormData(e.currentTarget),email=String(fd.get('email')),password=String(fd.get('password'));setUnconfirmedEmail(email);try{if(authMode==='up'){const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:SITE_URL}});if(error)throw error;setNotice(data.session?'🍄 Account created. Welcome to Quetopia.':'🍄 Check your email to verify your account, then return here and sign in.')}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;setNotice('Entering Quetopia…')}}catch(x:any){fail(x)}finally{setBusy(false)}}
  async function resendConfirmation(){if(!unconfirmedEmail)return;setBusy(true);setError('');try{const {error}=await supabase.auth.resend({type:'signup',email:unconfirmedEmail,options:{emailRedirectTo:SITE_URL}});if(error)throw error;setNotice('Fresh confirmation email sent. Check your inbox and use the newest link.')}catch(x:any){fail(x)}finally{setBusy(false)}}
  async function loadProfile(){if(!user)return;const {data,error}=await supabase.from('profiles').select('username,display_name,bio,city,region,public_contact,is_18_plus').eq('user_id',user.id).maybeSingle();if(error)return fail(error);if(data)setProfile({username:data.username??'',display_name:data.display_name??'',bio:data.bio??'',city:data.city??'',region:data.region??'',public_contact:data.public_contact??'',is_18_plus:!!data.is_18_plus})}
  async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user)return;setProfileBusy(true);setError('');setNotice('');try{const p={user_id:user.id,username:profile.username.trim(),display_name:profile.display_name.trim(),bio:profile.bio.trim(),city:profile.city.trim(),region:profile.region.trim(),country:'US',public_contact:profile.public_contact.trim(),is_18_plus:profile.is_18_plus};const {data,error}=await supabase.from('profiles').upsert(p,{onConflict:'user_id'}).select('username,display_name,bio,city,region,public_contact,is_18_plus').single();if(error)throw error;setProfile({username:data.username??'',display_name:data.display_name??'',bio:data.bio??'',city:data.city??'',region:data.region??'',public_contact:data.public_contact??'',is_18_plus:!!data.is_18_plus});setProfileExit(true);setTimeout(()=>{setProfileExit(false);setTab('home');setHomeFlash(true);window.scrollTo({top:0,behavior:'instant' as ScrollBehavior});setTimeout(()=>setHomeFlash(false),2600)},850)}catch(x:any){fail(x)}finally{setProfileBusy(false)}}
  async function sendChat(){if(!chat.trim())return;const next=[...messages,{role:'user',content:chat.trim()} as Msg];setMessages(next);setChat('');const {data,error}=await supabase.functions.invoke('ai-onboarding',{body:{messages:next}});if(error)return fail(error);setMessages([...next,{role:'assistant',content:data.message}])}
  async function syncAI(){const {error}=await supabase.functions.invoke('ai-profile-sync',{body:{messages}});if(error)return fail(error);flash('Your private AI profile is updated.')}
  async function createProject(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const p={owner_user_id:user.id,title:String(fd.get('title')),description:String(fd.get('description')||''),style_tags:String(fd.get('styles')||'').split(',').map(x=>x.trim()).filter(Boolean),location_mode:String(fd.get('location_mode')||'either'),city:String(fd.get('city')||''),region:String(fd.get('region')||''),country:'US',compensation:String(fd.get('compensation')||'open'),timeline_text:String(fd.get('timeline')||''),status:'active'};const {data:project,error:pe}=await supabase.from('projects').insert(p).select('*').single();if(pe)return fail(pe);const {data:r,error:re}=await supabase.from('project_roles').insert({project_id:project.id,role_name:String(fd.get('role_name')),description:String(fd.get('role_description')||''),required_skills:String(fd.get('required_skills')||'').split(',').map(x=>x.trim()).filter(Boolean),preferred_styles:String(fd.get('preferred_styles')||'').split(',').map(x=>x.trim()).filter(Boolean)}).select('*').single();if(re)return fail(re);const {error:se}=await supabase.functions.invoke('ai-project-role-sync',{body:{project_role_id:r.id}});if(se)return fail(se);flash('Project published and added to AI matching.');loadProjects();e.currentTarget.reset()}
  async function loadProjects(){const {data}=await supabase.from('projects').select('*,project_roles(*)').eq('owner_user_id',user.id).order('created_at',{ascending:false});setProjects(data??[])}
  async function loadMatches(){const {data}=await supabase.from('matches').select('*').order('compatibility_score',{ascending:false});setMatches(data??[])}
  async function generateMatches(){const {data,error}=await supabase.functions.invoke('ai-generate-matches',{body:{}});if(error)return fail(error);flash(`Evaluated ${data.evaluated??0} opportunities.`);loadMatches()}
  async function decide(id:string,decision:'approve'|'reject'){const {error}=await supabase.functions.invoke('match-decision',{body:{match_id:id,decision}});if(error)return fail(error);flash('Decision saved.');loadMatches()}

  if(!user)return <main className="landing"><section className="cosmicHero"><div className="heroGenerated" aria-label="Quetopia psychedelic cosmic art"><div className="orb"/><div className="silhouette">Q</div></div><div className="heroCopy"><div className="eyebrow">QUETOPIA // COLLAB NETWORK</div><h1>We create.<br/>We connect.<br/><span>We elevate.</span></h1><p>Your AI learns your sound, your vision, and your vibe—then finds the right humans to build something unforgettable.</p><div className="tagrow"><span className="tag">🎵 Musicians</span><span className="tag">🎥 Video Creators</span><span className="tag">✦ Visionaries</span></div></div></section><section className="authWrap"><form className="card" onSubmit={sign}><h2>{authMode==='in'?'🛸 ENTER QUETOPIA':'👁 CREATE ACCOUNT'}</h2>{notice&&<div className="status">{notice}</div>}{error&&<div className="status error">{error}</div>}<div className="field"><input name="email" type="email" placeholder="Email" required autoComplete="email"/></div><div className="field"><input name="password" type="password" placeholder="Password" minLength={8} required autoComplete={authMode==='in'?'current-password':'new-password'}/></div><button className="btn" disabled={busy}>{busy?(authMode==='in'?'ENTERING…':'CREATING ACCOUNT…'):(authMode==='in'?'SIGN IN →':'SIGN UP →')}</button>{authMode==='up'&&<p className="tiny muted">18+ only. Email verification required. 🍄</p>}{authMode==='in'&&/email not confirmed/i.test(error)&&<button type="button" className="linkbtn" onClick={resendConfirmation} disabled={busy}>Resend confirmation email →</button>}<button type="button" className="linkbtn" onClick={()=>{setAuthMode(authMode==='in'?'up':'in');setNotice('');setError('')}}>{authMode==='in'?'New here? Create an account →':'Already have an account? Sign in →'}</button></form><p className="brandbar">ENTER <span>QUETOPIA</span> — WHERE CREATIVITY MEETS CONNECTION.</p></section></main>

  const displayName=profile.display_name||profile.username||'Creator'
  const location=[profile.city,profile.region].filter(Boolean).join(', ')
  return <main className="shell">
    <div className="nav"><button className="btn secondary" onClick={()=>setTab('home')}>Home</button><button className="btn secondary" onClick={()=>setTab('matches')}>Matches</button><button className="btn secondary" onClick={()=>setTab('ai')}>My AI</button><button className="btn secondary" onClick={()=>setTab('projects')}>Projects</button><button className="btn secondary" onClick={()=>{setTab('profile');loadProfile()}}>Profile</button><button className="btn secondary" onClick={()=>supabase.auth.signOut()}>Sign out</button></div>
    {notice&&<div className="status">{notice}</div>}{error&&<div className="status error">{error}</div>}

    {tab==='home'&&<section className="dashboard"><div className={'profileHero '+(homeFlash?'profileHeroFlash':'')}><div className="avatarGlow">{displayName.slice(0,1).toUpperCase()}</div><div><div className="eyebrow">YOUR QUETOPIA SIGNAL</div><h1>{displayName}</h1>{profile.username&&<div className="handle">@{profile.username}</div>}{location&&<div className="location">✦ {location}</div>}</div></div>{homeFlash&&<div className="saveBurst"><span>PROFILE UPDATED</span><strong>YOUR SIGNAL JUST SHIFTED ✦</strong></div>}<div className="card profilePreview"><div className="previewHead"><h2>PUBLIC PROFILE</h2><button className="btn secondary" onClick={()=>{setTab('profile');loadProfile()}}>EDIT PROFILE</button></div><p className="bioText">{profile.bio||'Your bio will appear here. Tell people what you create, what you sound like, and what kind of collaborators you want to meet.'}</p><div className="profileFacts">{location&&<span className="pill">📍 {location}</span>}{profile.public_contact&&<span className="pill">✉ {profile.public_contact}</span>}{profile.is_18_plus&&<span className="pill">18+ verified</span>}</div></div><div className="grid dashboardGrid"><div className="card miniCard"><div className="eyebrow">MATCHES</div><div className="bigNumber">{matches.length}</div><p className="muted">AI-ranked creative connections.</p><button className="btn" onClick={()=>setTab('matches')}>EXPLORE MATCHES</button></div><div className="card miniCard"><div className="eyebrow">PROJECTS</div><div className="bigNumber">{projects.length}</div><p className="muted">Opportunities you have published.</p><button className="btn" onClick={()=>setTab('projects')}>OPEN PROJECTS</button></div></div></section>}

    {tab==='profile'&&<div className={profileExit?'profileStage evaporate':'profileStage'}><form className="card" onSubmit={saveProfile}><h2>PUBLIC PROFILE</h2><p className="muted">Edit what collaborators see. Your existing information stays loaded here until you change it.</p><div className="grid"><div className="field"><input name="username" value={profile.username} onChange={e=>setProfile({...profile,username:e.target.value})} placeholder="Username" required/></div><div className="field"><input name="display_name" value={profile.display_name} onChange={e=>setProfile({...profile,display_name:e.target.value})} placeholder="Display name"/></div><div className="field"><input name="city" value={profile.city} onChange={e=>setProfile({...profile,city:e.target.value})} placeholder="City"/></div><div className="field"><input name="region" value={profile.region} onChange={e=>setProfile({...profile,region:e.target.value})} placeholder="State / region"/></div></div><div className="field"><textarea name="bio" value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})} placeholder="Bio — what do you create, what is your vibe, and who do you want to meet?" rows={5}/></div><div className="field"><input name="public_contact" value={profile.public_contact} onChange={e=>setProfile({...profile,public_contact:e.target.value})} placeholder="Public contact email or method"/></div><label><input name="age" type="checkbox" checked={profile.is_18_plus} onChange={e=>setProfile({...profile,is_18_plus:e.target.checked})}/> I confirm I am 18 or older</label><p><button className="btn" disabled={profileBusy}>{profileBusy?'SAVING…':'SAVE PROFILE'}</button></p></form>{profileExit&&<div className="portalExit"><div className="portalRing"/><div className="portalText">SAVED TO QUETOPIA</div></div>}</div>}

    {tab==='ai'&&<section className="card"><h2>MY AI</h2><p className="muted">Talk naturally. Your structured collaboration profile stays private.</p>{messages.map((m,i)=><div className={'msg '+m.role} key={i}>{m.content}</div>)}<div className="field"><textarea value={chat} onChange={e=>setChat(e.target.value)} placeholder="Tell your AI what you make, who you're looking for, your style, deal-breakers..."/></div><div className="row"><button className="btn" onClick={sendChat}>SEND</button><button className="btn secondary" disabled={!messages.length} onClick={syncAI}>UPDATE MY AI PROFILE</button></div></section>}
    {tab==='projects'&&<><form className="card" onSubmit={createProject}><h2>CREATE OPPORTUNITY</h2><div className="field"><input name="title" placeholder="Project title" required/></div><div className="field"><textarea name="description" placeholder="What is this project?"/></div><div className="grid"><div className="field"><input name="role_name" placeholder="Role needed, e.g. guitarist" required/></div><div className="field"><input name="styles" placeholder="Project styles, comma-separated"/></div><div className="field"><input name="required_skills" placeholder="Required skills"/></div><div className="field"><input name="preferred_styles" placeholder="Preferred styles"/></div><div className="field"><select name="location_mode"><option value="either">Local or remote</option><option value="local">Local only</option><option value="remote">Remote only</option></select></div><div className="field"><select name="compensation"><option value="open">Compensation open</option><option value="paid">Paid</option><option value="unpaid">Unpaid</option><option value="barter">Barter</option></select></div><div className="field"><input name="city" placeholder="City"/></div><div className="field"><input name="region" placeholder="State / region"/></div></div><div className="field"><textarea name="role_description" placeholder="What do you need from this person?"/></div><div className="field"><input name="timeline" placeholder="Timeline"/></div><button className="btn">PUBLISH OPPORTUNITY</button></form>{projects.map(p=><div className="card" key={p.id}><h3>{p.title}</h3><p>{p.description}</p>{p.project_roles?.map((x:any)=><span className="pill" key={x.id}>{x.role_name}</span>)}</div>)}</>}
    {tab==='matches'&&<section><div className="card"><h2>YOUR AI MATCHES</h2><p className="muted">Personalized compatibility—not a universal rating.</p><button className="btn" onClick={generateMatches}>FIND MATCHES NOW</button></div>{matches.length===0&&<div className="card muted">No matches yet. Complete your profile, teach your AI, then generate matches.</div>}{matches.map(m=><article className="card" key={m.id}><div className="score">{m.compatibility_score}%</div><p>{m.explanation}</p>{Array.isArray(m.reasons?.items)&&m.reasons.items.map((x:string)=><span className="pill" key={x}>{x}</span>)}<p className="tiny muted">Status: {m.status}</p>{m.status==='proposed'&&<div className="row"><button className="btn" onClick={()=>decide(m.id,'approve')}>I'M INTERESTED</button><button className="btn danger" onClick={()=>decide(m.id,'reject')}>PASS</button></div>}</article>)}</section>}
  </main>
}
