'use client'

import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

type Profile={username:string;display_name:string;bio:string;city:string;region:string;public_contact:string;is_18_plus:boolean}
type Match={id:string;compatibility_score:number;explanation:string;reasons:any;status:string}
type Msg={role:'user'|'assistant';content:string}
type Nearby={user_id:string;username:string;display_name:string;bio:string;city:string;region:string;public_contact?:string;distance_miles:number;map_lat:number;map_lng:number}
const EMPTY:Profile={username:'',display_name:'',bio:'',city:'',region:'',public_contact:'',is_18_plus:false}
const SITE='https://quetopia-collab.vercel.app'
const AI_QUESTIONS=[
 'Nice. What does your ideal collaboration sound and feel like? Give me genres, influences, energy, or anything you want the other person to understand.',
 'What are the strongest skills you bring to a collaboration — instruments, production, songwriting, video, performance, or anything else?',
 'Who are you hoping Quetopia finds for you right now? Tell me the roles, skills, and vibe that would make someone a great fit.',
 'Do you want people nearby, remote collaborators, or either? And how far are you realistically willing to travel for the right project?',
 'What are your deal-breakers? Think commitment level, attitude, creative control, schedule, genre limits, or anything else that matters.',
 'Last one: what would make you see a match and immediately think, “Yep — I need to talk to this person”?'
]

export default function Home(){
 const [user,setUser]=useState<any>(null),[authMode,setAuthMode]=useState<'in'|'up'>('in'),[busy,setBusy]=useState(false)
 const [tab,setTab]=useState('home'),[notice,setNotice]=useState(''),[error,setError]=useState(''),[unconfirmed,setUnconfirmed]=useState('')
 const [profile,setProfile]=useState<Profile>(EMPTY),[profileLoading,setProfileLoading]=useState(false),[profileBusy,setProfileBusy]=useState(false),[evaporating,setEvaporating]=useState(false),[homeFlash,setHomeFlash]=useState(false)
 const [transitioning,setTransitioning]=useState(false),[transitionLabel,setTransitionLabel]=useState('')
 const [matches,setMatches]=useState<Match[]>([]),[projects,setProjects]=useState<any[]>([]),[messages,setMessages]=useState<Msg[]>([]),[chat,setChat]=useState(''),[aiBusy,setAiBusy]=useState(false),[aiNote,setAiNote]=useState('')
 const [nearby,setNearby]=useState<Nearby[]>([]),[myLoc,setMyLoc]=useState<{latitude:number;longitude:number}|null>(null),[locating,setLocating]=useState(false),[radius,setRadius]=useState(50)
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setUser(data.session?.user??null));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>subscription.unsubscribe()},[])
 useEffect(()=>{if(user){void loadProfile();void loadMatches();void loadProjects();void loadNearby();try{const raw=localStorage.getItem(`quetopia-ai-${user.id}`);if(raw)setMessages(JSON.parse(raw))}catch{}}},[user])
 useEffect(()=>{if(user&&tab==='profile')void loadProfile();if(user&&tab==='nearby')void loadNearby()},[tab,user,radius])
 const flash=(s:string)=>{setError('');setNotice(s);setTimeout(()=>setNotice(''),2600)}
 const fail=(e:any)=>{setNotice('');setError(e?.message??String(e))}
 const labels:any={home:'HOME SIGNAL',nearby:'SIGNAL MAP',matches:'MATCH ORBIT',ai:'MY AI',projects:'PROJECT SPACE',profile:'PUBLIC SIGNAL'}
 function go(next:string){if(next===tab||transitioning)return;setError('');setTransitionLabel(labels[next]||'QUETOPIA');setTransitioning(true);setTimeout(()=>{setTab(next);window.scrollTo({top:0,behavior:'instant' as ScrollBehavior})},360);setTimeout(()=>setTransitioning(false),820)}
 function saveMessages(m:Msg[]){setMessages(m);if(user)try{localStorage.setItem(`quetopia-ai-${user.id}`,JSON.stringify(m))}catch{}}
 const userAnswers=messages.filter(m=>m.role==='user').length
 const aiReady=userAnswers>=3
 function scanNetwork(){if(!aiReady){go('ai');return}void generateMatches()}
 function fallbackQuestion(answerCount:number){return AI_QUESTIONS[Math.min(Math.max(answerCount-1,0),AI_QUESTIONS.length-1)]}
 async function sign(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setNotice('');const fd=new FormData(e.currentTarget),email=String(fd.get('email')),password=String(fd.get('password'));setUnconfirmed(email);try{if(authMode==='up'){const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:SITE}});if(error)throw error;setNotice(data.session?'Welcome to Quetopia.':'Check your email to verify your account, then come back and sign in.')}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;setTab('home')}}catch(x:any){fail(x)}finally{setBusy(false)}}
 async function resend(){if(!unconfirmed)return;setBusy(true);const {error}=await supabase.auth.resend({type:'signup',email:unconfirmed,options:{emailRedirectTo:SITE}});setBusy(false);if(error)return fail(error);flash('Fresh confirmation email sent.')}
 async function loadProfile(){if(!user)return;setProfileLoading(true);setError('');try{const {data,error}=await supabase.from('profiles').select('username,display_name,bio,city,region,public_contact,is_18_plus').eq('user_id',user.id).maybeSingle();if(error)throw error;setProfile(data?{username:data.username??'',display_name:data.display_name??'',bio:data.bio??'',city:data.city??'',region:data.region??'',public_contact:data.public_contact??'',is_18_plus:!!data.is_18_plus}:EMPTY)}catch(x:any){fail(x)}finally{setProfileLoading(false)}}
 async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user)return;setProfileBusy(true);setError('');try{const p={user_id:user.id,username:profile.username.trim(),display_name:profile.display_name.trim(),bio:profile.bio.trim(),city:profile.city.trim(),region:profile.region.trim(),country:'US',public_contact:profile.public_contact.trim(),is_18_plus:profile.is_18_plus};const {data,error}=await supabase.from('profiles').upsert(p,{onConflict:'user_id'}).select('username,display_name,bio,city,region,public_contact,is_18_plus').single();if(error)throw error;setProfile({...p,...data});setEvaporating(true);setTimeout(()=>{setEvaporating(false);setTab('home');setHomeFlash(true);window.scrollTo({top:0,behavior:'instant' as ScrollBehavior});setTimeout(()=>setHomeFlash(false),2200)},900)}catch(x:any){fail(x)}finally{setProfileBusy(false)}}
 async function loadProjects(){if(!user)return;const {data}=await supabase.from('projects').select('*,project_roles(*)').eq('owner_user_id',user.id).order('created_at',{ascending:false});setProjects(data??[])}
 async function loadMatches(){const {data}=await supabase.from('matches').select('*').order('compatibility_score',{ascending:false});setMatches(data??[])}
 async function generateMatches(){const {data,error}=await supabase.functions.invoke('ai-generate-matches',{body:{}});if(error)return fail(error);flash(`Scanned ${data?.evaluated??0} opportunities.`);void loadMatches()}
 async function decide(id:string,decision:'approve'|'reject'){const {error}=await supabase.functions.invoke('match-decision',{body:{match_id:id,decision}});if(error)return fail(error);flash('Signal saved.');void loadMatches()}
 async function sendChat(){if(!chat.trim()||aiBusy)return;setError('');setAiNote('');const next=[...messages,{role:'user',content:chat.trim()} as Msg];saveMessages(next);setChat('');setAiBusy(true);try{const {data,error}=await supabase.functions.invoke('ai-onboarding',{body:{messages:next}});if(error)throw error;const reply=String(data?.message||data?.reply||'').trim();saveMessages([...next,{role:'assistant',content:reply||fallbackQuestion(next.filter(m=>m.role==='user').length)}])}catch{saveMessages([...next,{role:'assistant',content:fallbackQuestion(next.filter(m=>m.role==='user').length)}]);setAiNote('Signal received. I kept the conversation moving while the live AI connection reconnects.')}finally{setAiBusy(false)}}
 async function syncAI(){setAiNote('');const {error}=await supabase.functions.invoke('ai-profile-sync',{body:{messages}});if(error){setAiNote('Your answers are saved. Live AI profile sync is temporarily unavailable.');return}flash('Your AI signal is updated.')}
 async function createProject(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user)return;const fd=new FormData(e.currentTarget);const p={owner_user_id:user.id,title:String(fd.get('title')),description:String(fd.get('description')||''),style_tags:String(fd.get('styles')||'').split(',').map(x=>x.trim()).filter(Boolean),location_mode:String(fd.get('location_mode')||'either'),city:String(fd.get('city')||''),region:String(fd.get('region')||''),country:'US',compensation:String(fd.get('compensation')||'open'),timeline_text:String(fd.get('timeline')||''),status:'active'};const {data:project,error}=await supabase.from('projects').insert(p).select('*').single();if(error)return fail(error);const {error:roleError}=await supabase.from('project_roles').insert({project_id:project.id,role_name:String(fd.get('role_name')),description:String(fd.get('role_description')||''),required_skills:String(fd.get('required_skills')||'').split(',').map(x=>x.trim()).filter(Boolean),preferred_styles:String(fd.get('preferred_styles')||'').split(',').map(x=>x.trim()).filter(Boolean)});if(roleError)return fail(roleError);flash('Opportunity launched into Quetopia.');e.currentTarget.reset();void loadProjects()}
 async function loadNearby(){if(!user)return;const {data:loc}=await supabase.from('user_locations').select('latitude,longitude').eq('user_id',user.id).maybeSingle();if(!loc){setMyLoc(null);setNearby([]);return}setMyLoc(loc);const {data,error}=await supabase.rpc('nearby_profiles',{max_miles:radius});if(error)return fail(error);setNearby((data??[]) as Nearby[])}
 function locateMe(){if(!navigator.geolocation)return fail(new Error('Location is not available in this browser.'));setLocating(true);navigator.geolocation.getCurrentPosition(async pos=>{try{const point={user_id:user.id,latitude:pos.coords.latitude,longitude:pos.coords.longitude,updated_at:new Date().toISOString()};const {error}=await supabase.from('user_locations').upsert(point,{onConflict:'user_id'});if(error)throw error;setMyLoc({latitude:point.latitude,longitude:point.longitude});flash('Your signal location is locked in.');await loadNearby()}catch(x:any){fail(x)}finally{setLocating(false)}},err=>{setLocating(false);fail(new Error(err.message||'Could not access your location.'))},{enableHighAccuracy:true,timeout:12000,maximumAge:300000})}
 function pin(n:Nearby){if(!myLoc)return {left:'50%',top:'50%'};const latMiles=(n.map_lat-myLoc.latitude)*69,lngMiles=(n.map_lng-myLoc.longitude)*69*Math.cos(myLoc.latitude*Math.PI/180),scale=Math.max(radius,5);return {left:`${Math.max(7,Math.min(93,50+(lngMiles/scale)*44))}%`,top:`${Math.max(7,Math.min(93,50-(latMiles/scale)*44))}%`}}
 if(!user)return <main className="landing"><div className="ambient a1"/><div className="ambient a2"/><section className="loginPortal"><div className="sigil">Q</div><div className="eyebrow">QUETOPIA // COLLAB NETWORK</div><h1>FIND YOUR<br/><span>CREATIVE SIGNAL.</span></h1><p>AI-powered collaboration for musicians, creators and beautiful weirdos.</p><form className="glass" onSubmit={sign}>{notice&&<div className="notice">{notice}</div>}{error&&<div className="error">{error}</div>}<input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password" minLength={8} required/><button className="primary" disabled={busy}>{busy?'TUNING SIGNAL…':authMode==='in'?'ENTER QUETOPIA':'CREATE ACCOUNT'}</button>{authMode==='in'&&/email not confirmed/i.test(error)&&<button type="button" className="textBtn" onClick={resend}>Resend confirmation</button>}<button type="button" className="textBtn" onClick={()=>{setAuthMode(authMode==='in'?'up':'in');setError('');setNotice('')}}>{authMode==='in'?'New signal? Create account':'Already connected? Sign in'}</button></form></section></main>
 const name=profile.display_name||profile.username||'Creator',location=[profile.city,profile.region].filter(Boolean).join(', ')
 return <main className="shell"><div className="noise"/><header className="top"><button className="logo" onClick={()=>go('home')}>Q</button><nav>{[['home','Home'],['nearby','Nearby'],['matches','Matches'],['ai','My AI'],['projects','Projects'],['profile','Profile']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>go(k)}>{l}</button>)}</nav><button className="signout" onClick={()=>supabase.auth.signOut()}>↗</button></header>
 {transitioning&&<div className="pagePortal"><div className="pageWarp"><i/><i/><i/></div><b>{transitionLabel}</b></div>}{notice&&<div className="toast">✦ {notice}</div>}{error&&<div className="toast bad">{error}</div>}
 {tab==='home'&&<section className="home pageIn"><div className={'identity '+(homeFlash?'flash':'')}><div className="avatar">{name[0]?.toUpperCase()}</div><div><div className="eyebrow">YOUR QUETOPIA SIGNAL</div><h1>{name}</h1>{profile.username&&<div className="handle">@{profile.username}</div>}{location&&<div className="location">◉ {location}</div>}</div></div>{homeFlash&&<div className="shift">PROFILE UPDATED <b>YOUR SIGNAL SHIFTED ✦</b></div>}<div className="profileCard glass"><div className="cardHead"><div><div className="eyebrow">PUBLIC SIGNAL</div><h2>Your profile</h2></div><button className="ghost" onClick={()=>go('profile')}>EDIT</button></div><p>{profile.bio||'Add a bio so collaborators immediately understand your sound, vision and vibe.'}</p><div className="chips">{location&&<span>📍 {location}</span>}{profile.public_contact&&<span>✉ {profile.public_contact}</span>}{profile.is_18_plus&&<span>✓ 18+</span>}</div></div><div className="metrics"><button className="metric" onClick={()=>go('nearby')}><small>NEARBY SIGNALS</small><strong>{nearby.length}</strong><span>Open signal map →</span></button><button className="metric" onClick={()=>go('matches')}><small>MATCH SIGNALS</small><strong>{matches.length}</strong><span>Explore connections →</span></button><button className="metric" onClick={()=>go('projects')}><small>ACTIVE PROJECTS</small><strong>{projects.length}</strong><span>Build something →</span></button></div></section>}
 {tab==='nearby'&&<section className="nearbyStage pageIn"><div className="glass mapHero"><div><div className="eyebrow">LOCAL CREATIVE RADAR</div><h1>Signal map</h1><p>See creators around you by distance. Your exact GPS coordinates stay private; other people only receive an approximate map position and distance.</p></div><div className="mapControls"><button className="primary" onClick={locateMe} disabled={locating}>{locating?'LOCKING ON…':myLoc?'REFRESH MY LOCATION':'USE MY GPS'}</button><label>Range <select value={radius} onChange={e=>setRadius(Number(e.target.value))}><option value={10}>10 mi</option><option value={25}>25 mi</option><option value={50}>50 mi</option><option value={100}>100 mi</option></select></label></div></div>{myLoc?<><div className="signalMap glass"><div className="radarRing r1"/><div className="radarRing r2"/><div className="radarRing r3"/><div className="radarSweep"/><button className="mePin">YOU</button>{nearby.map(n=><button key={n.user_id} className="creatorPin" style={pin(n)}><span>{(n.display_name||n.username||'?')[0]?.toUpperCase()}</span><small>{n.distance_miles<1?'<1':n.distance_miles.toFixed(1)} mi</small></button>)}</div><div className="nearbyList">{nearby.length===0?<div className="empty glass">No other Quetopia signals are broadcasting within {radius} miles yet.</div>:nearby.map(n=><article className="glass nearbyCard" key={n.user_id}><div className="avatar mini">{(n.display_name||n.username||'?')[0]?.toUpperCase()}</div><div><div className="eyebrow">{n.distance_miles.toFixed(1)} MILES AWAY</div><h2>{n.display_name||n.username}</h2>{n.username&&<div className="handle">@{n.username}</div>}<p>{n.bio||'No bio yet.'}</p></div></article>)}</div></>:<div className="glass locationGate"><div className="loaderOrb"/><h2>Broadcast your signal</h2><p>Tap <b>USE MY GPS</b> and allow location access.</p></div>}</section>}
 {tab==='profile'&&<section className={'profileStage pageIn '+(evaporating?'evaporate':'')}>{profileLoading?<div className="profileLoader"><div className="loaderOrb"/><p>RECALLING YOUR SIGNAL…</p></div>:<form className="glass profileForm" onSubmit={saveProfile}><div className="eyebrow">PUBLIC PROFILE</div><h1>Edit your signal</h1><p className="sub">Your saved information is loaded first. Change only what you want.</p><div className="two"><label><span>Username</span><input value={profile.username} onChange={e=>setProfile({...profile,username:e.target.value})}/><small>Your unique @handle shown across Quetopia.</small></label><label><span>Display name</span><input value={profile.display_name} onChange={e=>setProfile({...profile,display_name:e.target.value})}/><small>The name collaborators see on your profile.</small></label><label><span>City</span><input value={profile.city} onChange={e=>setProfile({...profile,city:e.target.value})}/></label><label><span>State / region</span><input value={profile.region} onChange={e=>setProfile({...profile,region:e.target.value})}/></label></div><label><span>Bio</span><textarea rows={5} value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})}/></label><label><span>Public contact</span><input value={profile.public_contact} onChange={e=>setProfile({...profile,public_contact:e.target.value})}/></label><label className="check"><input type="checkbox" checked={profile.is_18_plus} onChange={e=>setProfile({...profile,is_18_plus:e.target.checked})}/> I confirm I am 18 or older</label><button className="primary save" disabled={profileBusy}>{profileBusy?'SAVING TO THE SIGNAL…':'SAVE + RETURN HOME'}</button></form>}{evaporating&&<div className="portal"><div className="ring"/><b>SAVED TO QUETOPIA</b></div>}</section>}
 {tab==='matches'&&<section className="stack pageIn"><div className="glass heroCard"><div className="eyebrow">AI MATCH ENGINE</div><h1>Your creative orbit</h1><p>Compatibility is personal—not a popularity score.</p><button className="primary" onClick={scanNetwork}>{aiReady?'SCAN THE NETWORK':'TEACH MY AI FIRST'}</button>{!aiReady&&<p className="sub">Answer a few quick My AI questions first so matches are actually meaningful.</p>}</div>{matches.length===0&&<div className="empty glass">{aiReady?'No signals yet. Scan the network to discover collaborators.':'Teach My AI about your sound, goals and collaborators, then return here to scan the network.'}</div>}{matches.map(m=><article className="match glass" key={m.id}><div className="score">{m.compatibility_score}<small>%</small></div><p>{m.explanation}</p>{m.status==='proposed'&&<div className="actions"><button className="primary" onClick={()=>decide(m.id,'approve')}>CONNECT</button><button className="ghost" onClick={()=>decide(m.id,'reject')}>PASS</button></div>}</article>)}</section>}
 {tab==='ai'&&<section className="glass ai pageIn"><div className="eyebrow">YOUR PRIVATE COLLABORATION INTELLIGENCE</div><h1>{messages.length?'My AI':'Tune your creative signal'}</h1><p className="sub">{messages.length?'Keep teaching it your sound, taste, goals and deal-breakers. Each answer sharpens who Quetopia should put in your orbit.':'Start with what you create and who you want to find. My AI will take it from there one question at a time.'}</p>{!messages.length&&<div className="chips"><span>✦ Your sound</span><span>✦ Your goals</span><span>✦ Skills you bring</span><span>✦ People you need</span></div>}<div className="chat">{messages.map((m,i)=><div className={'bubble '+m.role} key={i}>{m.content}</div>)}{aiBusy&&<div className="bubble assistant">Tuning into your signal…</div>}</div>{aiNote&&<div className="notice">✦ {aiNote}</div>}<textarea rows={4} value={chat} onChange={e=>setChat(e.target.value)} placeholder={messages.length?'Answer the question above…':'Example: I’m a groove-oriented bassist looking for musicians who want to build original, adventurous music…'}/><div className="actions"><button className="primary" disabled={aiBusy||!chat.trim()} onClick={sendChat}>{aiBusy?'LISTENING…':'SEND SIGNAL'}</button><button className="ghost" disabled={!messages.length||aiBusy} onClick={syncAI}>SYNC MY AI</button></div></section>}
 {tab==='projects'&&<section className="stack pageIn"><div className="glass heroCard"><div className="eyebrow">PROJECT SPACE</div><h1>Build something weird.</h1><p>Post what you're making and exactly who you need.</p></div><form className="glass projectForm" onSubmit={createProject}><input name="title" placeholder="Project title" required/><textarea name="description" placeholder="What are you making?"/><input name="styles" placeholder="Styles / influences, comma separated"/><div className="two"><select name="location_mode"><option value="either">Local or remote</option><option value="local">Local only</option><option value="remote">Remote only</option></select><input name="timeline" placeholder="Timeline"/><input name="city" placeholder="City"/><input name="region" placeholder="State / region"/></div><input name="role_name" placeholder="Who do you need? e.g. Vocalist" required/><textarea name="role_description" placeholder="Describe the role"/><input name="required_skills" placeholder="Required skills, comma separated"/><input name="preferred_styles" placeholder="Preferred styles, comma separated"/><button className="primary">LAUNCH OPPORTUNITY</button></form>{projects.map(p=><article className="glass project" key={p.id}><div className="eyebrow">{p.status}</div><h2>{p.title}</h2><p>{p.description}</p></article>)}</section>}
 </main>
}
