import * as THREE from '../grove/vendor/three/three.module.js';
import {mergeGeometries} from '../grove/vendor/three/BufferGeometryUtils.js';
import {GLTFLoader} from '../grove/vendor/three/GLTFLoader.js';
export function createActors(){
 const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});renderer.setSize(320,320,false);renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
 const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-1.55,1.55,1.55,-1.55,.1,30);camera.position.set(0,2.5,6);camera.lookAt(0,1.1,0);scene.add(new THREE.HemisphereLight(0xece1ff,0x343320,2.3));const light=new THREE.DirectionalLight(0xffe2c1,3);light.position.set(-3,5,4);scene.add(light);const rim=new THREE.DirectionalLight(0x99ccff,2);rim.position.set(3,3,-4);scene.add(rim);
 const cache=new Map();let active=null;
 const load=async id=>{if(cache.has(id))return cache.get(id);const url=id==='suneye'?'../model-studies/suneye/Suneye-study.glb':`../model-studies/${id}/${id}.glb`;const gltf=await new GLTFLoader().loadAsync(url);let model=gltf.scene;model.updateMatrixWorld(true);const batches=new Map();model.traverse(o=>{if(o.isMesh&&!o.isSkinnedMesh&&!Array.isArray(o.material)){const key=o.material.uuid;const batch=batches.get(key)||{material:o.material,geometries:[]};batch.geometries.push(o.geometry.clone().applyMatrix4(o.matrixWorld));batches.set(key,batch);}});if(batches.size&&id==='suneye'){const compact=new THREE.Group();for(const b of batches.values()){const merged=mergeGeometries(b.geometries);if(merged)compact.add(new THREE.Mesh(merged,b.material));for(const g of b.geometries)g.dispose();}if(compact.children.length===batches.size)model=compact;}else{for(const b of batches.values())for(const g of b.geometries)g.dispose();}const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const scale=2/Math.max(size.y,size.x*.65,size.z*.65);model.scale.multiplyScalar(scale);model.position.set(-center.x*scale,-box.min.y*scale,-center.z*scale);const group=new THREE.Group();group.add(model);group.visible=false;scene.add(group);const data={group,angle:0,last:null,bob:0};cache.set(id,data);return data;};
 return {async prepare(spec){await Promise.all([load(spec.id),load(spec.petId)]);},draw(ctx,p,id,height,dt,playing){const d=cache.get(id);if(!d)return false;if(active)active.group.visible=false;active=d;d.group.visible=true;const delta=Math.atan2(Math.sin((p.heading||0)-d.angle),Math.cos((p.heading||0)-d.angle));d.angle+=delta*(1-Math.exp(-12*dt));d.group.rotation.y=d.angle;const moving=d.last&&Math.hypot(p.x-d.last.x,p.y-d.last.y)>.02;if(playing&&moving)d.bob+=dt*10;d.group.position.y=playing&&moving?Math.sin(d.bob)*.035:0;d.group.rotation.z=playing&&moving?Math.sin(d.bob*.5)*.025:0;d.last={x:p.x,y:p.y};renderer.render(scene,camera);const width=height*1.35;ctx.drawImage(renderer.domElement,p.x-width/2,p.y-height*1.08,width,width);return true;},reset(){for(const d of cache.values())d.last=null;}};
}
