import {Grove as RosterGrove,distance} from './simulation.mjs';
export {W,H,WAND_CHARGE,SKILLS,BLESSINGS,distance} from './simulation.mjs';
export const CHAPTERS=[
 {id:'roots',title:'The Root That Remembered',region:'I · The Fractured Grove',requires:[],kind:'ritual',goal:3,boss:'The Thorn Crown',color:'#679b62',art:'druid',speaker:'Mushroom Druid',line:'Punkin found a root the Curator insists never existed. Follow her. Things do not need permission to grow.',story:'The same leaf falls every morning. No seed survives the reset. Awaken the three root memories and break the guardian that keeps this day repeating.',after:'A crooked sapling survives its first tomorrow. Beyond its roots, two impossible roads appear: a sea that remembers light and a moon that remembers sleep.',reward:'Wild Growth · +12 maximum life',hp:12,damage:0},
 {id:'tide',title:'The Sunrise Beneath the Sea',region:'II · The Prism Undertow',requires:['roots'],kind:'hunt',goal:10,boss:'The Perfect Reflection',color:'#2b9eae',art:'reef-lobster',speaker:'Diamond Girl',line:'Suneye remembers a sunrise no mirror will admit. Reef Lobster can hear it beneath the tide.',story:'The Curator replaced every possible future with one polished reflection. Defeat ten glassbound creatures, then attune the drowned lens to call its keeper.',after:'The lens breaks into colors without names. The sea returns one lost possibility: you were allowed to become someone else.',reward:'Unwritten Spectrum · +3% damage',hp:0,damage:.03},
 {id:'moon',title:'A Bed for the Restless Moon',region:'III · The Sleepless Observatory',requires:['roots'],kind:'ritual',goal:2,boss:'The Bell That Never Sleeps',color:'#7266b4',art:'crescent-weaver',speaker:'Crescent Weaver',line:'Orrery Moth has carried the same dream for a thousand nights. Let us give it somewhere to land.',story:'No one dreams in the perfect day. Unfasten two clock anchors while the observatory tries to strike the hour through you. Silence its bell.',after:'For one breath the clock stops. Across Quetopia, sleepers see lives they have never lived. Even the Curator dreams—and wakes frightened.',reward:'Restful Orbit · +12 maximum life',hp:12,damage:0},
 {id:'carnival',title:'The Joke With No Punchline',region:'IV · The Carnival of Almost',requires:['tide','moon'],kind:'survive',goal:35,boss:'The Applause Machine',color:'#b5518d',art:'sally',speaker:'Sally',line:'Spark Imp, darling, if they demand a perfect performance, we shall give them a beautiful disaster.',story:'Every laugh here is played from a recording. Keep the unscripted signal alive for 35 seconds, then attune the stage relay. Stay out of the falling spotlights.',after:'Someone laughs at the wrong moment. The crowd joins in. Under the stage, Cyberdine finds the order that made every memory identical.',reward:'Beautiful Disorder · +3% damage',hp:0,damage:.03},
 {id:'archive',title:'What the Fire Refused to Burn',region:'V · The Cinder Archive',requires:['carnival'],kind:'ritual',goal:3,boss:'The Mercy Engine',color:'#b86639',art:'cyberdine',speaker:'Cyberdine',line:'Lens Wisp found the missing stitches. Ember Sovereign, keep your fire low. These records are people.',story:'Unseal three memory vaults as the archive burns. Cinderling discovers the first erased memory: the Curator once lost someone, and mistook preventing grief for preventing life.',after:'You save the record of a small ordinary goodbye. The Curator finally remembers why it built the loop. Its final defense opens above the archive.',reward:'Cinder Promise · +12 maximum life',hp:12,damage:0},
 {id:'veil',title:'A Tomorrow Without Permission',region:'VI · The Unwritten Heart',requires:['archive'],kind:'ritual',goal:2,boss:'The Curator',color:'#a86abc',art:'diamond-girl',speaker:'The Curator',line:'I kept every last good moment safe. Why do you call that a prison?',story:'Release the two certainty locks. Defeat the Curator’s last defense while the heart tears holes in the repeating day. Then decide what should become of its keeper.',after:'The loop is broken. Punkin follows a root into soil that has never known a footstep. Every companion hears the same thing: tomorrow arriving.',reward:'The Open Veil · +3% damage',hp:0,damage:.03}
];
export function cleanCampaign(value){const ids=new Set(CHAPTERS.map(c=>c.id));return {completed:[...new Set(Array.isArray(value?.completed)?value.completed.filter(x=>ids.has(x)):[])],ending:['mercy','release'].includes(value?.ending)?value.ending:null};}
export function unlocked(c,state){return c.requires.every(id=>state.completed.includes(id));}
export function completeChapter(state,id){const s=cleanCampaign(state),c=CHAPTERS.find(c=>c.id===id);if(!c||!unlocked(c,s)||s.completed.includes(id))return s;s.completed.push(id);return s;}
export class Grove extends RosterGrove {
 reset(){super.reset();this.chapter=null;this.hazards=[];this.hazardClock=4;this.waveClock=6;}
 loadChapter(id,state){if(this.mode==='playing')return false;const c=CHAPTERS.find(c=>c.id===id),save=cleanCampaign(state);if(!c||!unlocked(c,save))return false;this.reset();this.chapter=c;this.chapterIndex=CHAPTERS.indexOf(c);const earned=CHAPTERS.filter(x=>save.completed.includes(x.id));this.player.maxHp+=earned.reduce((n,x)=>n+x.hp,0);this.player.hp=this.player.maxHp;this.power+=earned.reduce((n,x)=>n+x.damage,0);this.enemies=[];this.events=[];const positions=[{x:425,y:330},{x:1090,y:415},{x:760,y:775}];this.anchors=positions.slice(0,c.kind==='ritual'?c.goal:1).map(p=>({...p,on:false}));this.spawnWave(4);return true;}
 start(){super.start();if(this.chapter){this.events=[];this.event('notice',this.player,{text:this.chapter.title});}}
 spawn(x,y,boss){super.spawn(x,y,boss);if(this.chapter){const e=this.enemies.at(-1);e.hp*=1+this.chapterIndex*.10;e.maxHp=e.hp;}}
 get objective(){const c=this.chapter;if(!c)return 'Awaken the root seals';if(this.bossSpawned)return 'Defeat '+c.boss;if(c.kind==='hunt'&&this.kills<c.goal)return `Break the glassbound · ${Math.min(this.kills,c.goal)} / ${c.goal}`;if(c.kind==='survive'&&this.time<c.goal)return `Keep the signal alive · ${Math.ceil(c.goal-this.time)}s`;return c.kind==='ritual'?`Release the memory anchors · ${this.encounter} / ${c.goal}`:'Attune the relay · F';}
 attune(){if(!this.chapter)return super.attune();if(this.mode!=='playing')return false;const c=this.chapter;if((c.kind==='hunt'&&this.kills<c.goal)||(c.kind==='survive'&&this.time<c.goal)){this.event('notice',this.player,{text:this.objective});return false;}const a=this.anchors.find(a=>!a.on&&distance(a,this.player)<105);if(!a)return false;if(this.enemies.some(e=>!e.dead&&distance(e,a)<180)){this.event('notice',a,{text:'Clear the creatures around this memory.'});return false;}a.on=true;this.encounter++;this.recover(50,0);this.player.mana=100;this.event('anchor',a);if(this.anchors.every(a=>a.on)){this.bossSpawned=true;this.spawn(768,290,true);this.event('notice',a,{text:c.boss.toUpperCase()});}else this.spawnWave(3+this.encounter);return true;}
 step(dt,input={}){if(this.mode!=='playing')return;super.step(dt,input);if(!this.chapter||this.mode!=='playing')return;const c=this.chapter;this.waveClock-=dt;if(!this.bossSpawned&&this.waveClock<=0){this.waveClock=7;const alive=this.enemies.filter(e=>!e.dead).length;if((c.kind==='hunt'&&this.kills<c.goal)||c.kind==='survive'&&this.time<c.goal)this.spawnWave(Math.min(3,Math.max(0,10-alive)));}
 for(const h of this.hazards){h.life-=dt;if(h.life<=0){this.event('strike',h,{r:h.r});if(distance(this.player,h)<h.r)this.hurt(25+this.chapterIndex*2);}}this.hazards=this.hazards.filter(h=>h.life>0);
 if(this.chapterIndex>=2){this.hazardClock-=dt;if(this.hazardClock<=0){this.hazardClock=this.bossSpawned?3.5:6;const count=this.chapterIndex===5&&this.bossSpawned?3:1;for(let i=0;i<count;i++){const h={x:i?430+i*300:this.player.x,y:i?400:this.player.y,r:c.id==='archive'?100:75,life:1.5};this.hazards.push(h);this.event('telegraph',h,{r:h.r,life:h.life});}}}
 }
}
