import {CHAPTERS,cleanCampaign,unlocked,completeChapter} from './campaign.mjs';
export function setupCampaign({game,start,clearEffects,art}){
 const $=s=>document.querySelector(s),key='quetopia.campaign.v1';let saves={},saveOK=true;
 try{saves=JSON.parse(localStorage.getItem(key)||'{}');if(!saves||typeof saves!=='object'||Array.isArray(saves))saves={};}catch{saveOK=false;}
 const state=()=>cleanCampaign(saves[game.character]);
 const persist=s=>{saves[game.character]=s;try{localStorage.setItem(key,JSON.stringify(saves));saveOK=true;}catch{saveOK=false;}};
 const panel=document.createElement('div');panel.id='campaignPanel';panel.className='overlay';panel.hidden=true;
 panel.innerHTML='<section><small class="eyebrow">THE UNWRITTEN SIGNAL</small><h1>Your next<br><em>tomorrow.</em></h1><p id="campaignSummary"></p><div id="chapterGrid"></div><article id="chapterDetail" hidden><img id="chapterArt" alt=""><div><small id="chapterRegion"></small><h2 id="chapterTitle"></h2><p id="chapterStory"></p><blockquote id="chapterDialogue"></blockquote><p id="chapterReward"></p><button id="beginChapter">Begin chapter</button></div></article><button id="closeCampaign">Back to characters</button><p id="campaignSave" role="status"></p><small>Campaign prototype · six missions share the grove arena.</small></section>';
 document.body.append(panel);let selected=null;
 function detail(c){selected=c;$('#chapterDetail').hidden=false;$('#chapterArt').src=art(c.art);$('#chapterArt').alt=c.art==='reef-lobster'?'Reef Lobster':c.speaker;$('#chapterRegion').textContent=c.region;$('#chapterTitle').textContent=c.title;$('#chapterStory').textContent=c.story;$('#chapterDialogue').textContent=c.speaker+': “'+c.line+'”';$('#chapterReward').textContent=(state().completed.includes(c.id)?'Already earned: ':'First completion: ')+c.reward;$('#beginChapter').textContent=state().completed.includes(c.id)?'Replay chapter':'Begin chapter';for(const b of $('#chapterGrid').children)b.setAttribute('aria-pressed',b.dataset.id===c.id);}
 function open(){if(game.mode==='playing')return;const s=state();panel.hidden=false;$('#menu').hidden=true;$('#end').hidden=true;$('#chapterGrid').replaceChildren();$('#chapterDetail').hidden=true;$('#campaignSummary').textContent=game.spec.name+' & '+game.spec.pet+' · '+s.completed.length+' / 6 chapters restored'+(s.ending?' · Ending: '+(s.ending==='mercy'?'The Keeper of Uncertain Things':'The Open Door'):'');$('#campaignSave').textContent=saveOK?'Completed chapters and rewards save on this browser. Defeat restarts only the current mission.':'Saving is unavailable. Progress lasts for this session.';for(const c of CHAPTERS){const b=document.createElement('button');b.dataset.id=c.id;b.disabled=!unlocked(c,s);b.textContent=c.region+' — '+c.title+(s.completed.includes(c.id)?' ✓':b.disabled?' · Locked':'');b.onclick=()=>detail(c);$('#chapterGrid').append(b);}detail(CHAPTERS.find(c=>unlocked(c,s)&&!s.completed.includes(c.id))||CHAPTERS[0]);$('#beginChapter').focus();}
 function begin(c){if(!c||!game.loadChapter(c.id,state()))return;clearEffects();panel.hidden=true;$('#menu').hidden=true;$('#end').hidden=true;document.querySelector('.quest small').textContent=c.region;document.querySelector('.quest h2').textContent=c.title;document.querySelector('.quest .hint').textContent='Clear nearby enemies · F to attune';$('#boss strong').textContent=c.boss;$('#boss small').textContent='KEEPER OF THE REPEATING DAY';document.querySelector('.brand small').textContent=c.region;start();}
 $('#beginChapter').onclick=()=>begin(selected);$('#closeCampaign').onclick=()=>{panel.hidden=true;$('#menu').hidden=false;$('#start').focus();};$('#start').onclick=open;
 const onward=document.createElement('button');onward.id='campaignContinue';onward.textContent='Continue the campaign';onward.onclick=open;$('#restart').before(onward);
 const ending=document.createElement('div');ending.id='endingChoice';ending.hidden=true;ending.innerHTML='<p>The Curator is defeated. What becomes of its keeper?</p><button data-ending="mercy">Teach it to live with uncertainty</button><button data-ending="release">Let it go; leave the door open</button><p id="endingText" role="status"></p>';onward.before(ending);
 for(const b of ending.querySelectorAll('button'))b.onclick=()=>{const s=state();if(!s.completed.includes('veil'))return;s.ending=b.dataset.ending;persist(s);$('#endingText').textContent=s.ending==='mercy'?'The Curator becomes a gardener. It plants its first seed without knowing what will grow.':'The Curator sets down its keys and walks beyond the veil. No one tells it which road to take.';for(const x of ending.querySelectorAll('button'))x.setAttribute('aria-pressed',x===b);};
 $('#restart').onclick=()=>{const c=game.chapter;if(c)begin(c);else{game.reset();clearEffects();start();}};
 return {onEnd(){if(!game.chapter)return;const won=game.mode==='won',c=game.chapter;onward.hidden=!won;ending.hidden=!(won&&c.id==='veil');$('#endingText').textContent='';$('#restart').textContent=won?'Replay this chapter':'Retry this chapter';$('#endLabel').textContent=won?'CHAPTER RESTORED':game.spec.pet.toUpperCase()+' WILL FIND YOU AGAIN';$('#endStats').textContent=won?c.after:'The memory is still waiting. Your completed chapters and their rewards are safe.';if(won){persist(completeChapter(state(),c.id));$('#endStats').textContent+=' '+c.reward+'.';}$('#campaignSave').textContent=saveOK?'Progress saved.':'Progress could not be saved; keep this tab open.';},open};
}
