// Starter kits for The Unwritten Signal. Advanced trees remain in the design document.
const skill=(name,cost,cd,description)=>({name,cost,cd,description});
export const ROSTER=[
 {id:'druid',name:'Mushroom Druid',title:'Keeper of Unscripted Things',pet:'Punkin',petId:'punkin',color:'#aed789',role:'Sustain · spores · close companion',story:'When the Curator erased the untidy parts of life, the grove stopped growing. Only Punkin remembered where the wild roots went.',promise:'Let the imperfect things grow.',hp:240,skills:[skill('Spore lance',0,.32,'A piercing seed projectile.'),skill('Mycelial ring',28,4,'Damage nearby creatures.'),skill('Barkmemory',22,6,'Root and damage a group at the cursor.'),skill('Elder bloom',30,10,'Restore 95 life and briefly evade damage.')],builds:['Living Orchard','Amber Needle','Hearthbound']},
 {id:'diamond-girl',name:'Diamond Girl',title:'Prism Oracle',pet:'Suneye',petId:'suneye',color:'#d9a6ff',role:'Ranged · piercing rays · mirror echoes',story:'The Curator polished every future into the same diamond. She broke her crown to let the other possibilities shine. Suneye kept the first forbidden sunrise.',promise:'There is more than one beautiful future.',hp:205,skills:[skill('Prism ray',0,.42,'A fast ray that pierces two creatures.'),skill('Mirrorseed',24,5,'Plant two mirrors that echo your next rays for 6 seconds.'),skill('Facet ward',20,7,'Heal 45 life and gain brief protection.'),skill('Spectrum break',38,10,'Send twelve piercing rays outward.')],builds:['Kaleidoscope','White Needle','Living Lens']},
 {id:'crescent-weaver',name:'Crescent Weaver',title:'Keeper of the Missing Hour',pet:'Orrery Moth',petId:'orrery-moth',color:'#aebfff',role:'Cycles · control · lunar bursts',story:'She found an hour that no clock would admit existed. Inside it, an orrery moth was still circling a child’s unfinished dream.',promise:'No dream has to end on schedule.',hp:220,skills:[skill('Moon arc',0,.48,'Twin crescent bolts; every third cast is an eclipse burst.'),skill('Stillwater hour',26,6,'Hold creatures near the cursor for 3 seconds.'),skill('Borrowed moment',22,8,'Restore life and reset your dodge cooldown.'),skill('Eclipse',38,11,'Damage and bind creatures in a wide circle.')],builds:['Eclipse Artillery','Endless Dusk','Lunar Escort']},
 {id:'ember-sovereign',name:'Ember Sovereign',title:'The Unextinguished',pet:'Cinderling',petId:'cinderling',color:'#ff9663',role:'Close range · heat · explosive release',story:'Ordered to burn the world’s unwanted memories, the Sovereign hid one ember beneath a broken scale. It hatched, and refused to obey.',promise:'We choose what the fire protects.',hp:285,skills:[skill('Cinder claw',0,.5,'Slash a short forward cone; generates 12 Heat.'),skill('Furnace breath',0,4,'Burn a broad cone; generates 20 Heat.'),skill('Venting scales',0,7,'Vent 35 Heat, heal 45 life and gain protection.'),skill('Worldfire',0,10,'Spend 40 Heat in an enormous fiery pulse.')],builds:['Ashgarden','Furnace Guardian','Last Match']},
 {id:'sally',name:'Sally',title:'The Unscheduled Encore',pet:'Spark Imp',petId:'spark-imp',color:'#ff99cc',role:'Traps · chain reactions · fireworks',story:'Her carnival was condemned for making people laugh at the wrong moment. Sally stole the ending of its final show. Spark Imp still carries the fuse.',promise:'The punchline belongs to everybody.',hp:215,skills:[skill('Sugarshot',0,.36,'Fire a three-shot candy spread.'),skill('Gumdrop',22,3,'Place a timed explosive at the cursor, up to three.'),skill('Emergency encore',20,7,'Scatter nearby enemies and recover 50 life.'),skill('Punchline',35,9,'Detonate all gumdrops, then rain a burst at the cursor.')],builds:['Grand Finale','Travelling Carnival','Sugar Rush']},
 {id:'cyberdine',name:'Cyberdine',title:'Archivist of Lost Faces',pet:'Lens Wisp',petId:'lens-wisp',color:'#87eadb',role:'Marks · focused damage · repair',story:'Every stitch holds a face the Curator tried to delete. Lens Wisp shows the seams between official history and the people who actually lived it.',promise:'A scar is proof that something survived.',hp:235,skills:[skill('Seam needle',0,.4,'Piercing needle; deals bonus damage to Frayed enemies.'),skill('Threadbind',24,5,'Mark and bind a cluster for 5 seconds.'),skill('Recompose',26,8,'Restore 75 life; damage marked creatures.'),skill('Open the seam',36,10,'Rupture enemies near the cursor; Frayed targets take double damage.')],builds:['Unravelling Web','Surgical Precision','Restitched']},
 {id:'abyssal-cantor',name:'Abyssal Cantor',title:'Voice Beneath the Silence',pet:'Reef Lobster',petId:'reef-lobster',color:'#71dbea',role:'Tidal zones · setup · wave bursts',story:'The ocean forgot its own song. Beneath the silence, a lobster tapped the rhythm against a sealed door. The Cantor answered.',promise:'Even the quietest voice makes a tide.',hp:255,skills:[skill('Undertone',0,.46,'Three tidal notes spread outward.'),skill('Resonant pool',26,5,'Create a 5-second damaging pool that Soaks enemies.'),skill('Shellsong',24,8,'Restore 65 life and gain a protective beat.'),skill('Breakwater',38,10,'Smash nearby enemies; Soaked creatures take double damage.')],builds:['Breakwater Hammer','Salt Cathedral','Reefwarden']}
];
export const byId=id=>ROSTER.find(c=>c.id===id)||ROSTER[0];
export const IDS=['bolt','nova','roots','heal'];
export function kitFor(id){const c=byId(id);return Object.fromEntries([...c.skills.map((s,i)=>[IDS[i],{...s,key:['Q','W','E','R'][i]}]),['dash',{name:'Veil step',cost:0,cd:1.6,key:'SPACE',description:'Slide through the veil toward the cursor.'}]]);}
